---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: certificate
  namespace: sthlmio
spec:
  secretName: certificate-secret
  dnsNames:
    - sthlm.io
    - www.sthlm.io
    - stockholm.io
    - www.stockholm.io
  issuerRef:
    name: cluster-issuer-cloudflare-prod
    kind: ClusterIssuer
    group: cert-manager.io