---
apiVersion: projectcontour.io/v1
kind: HTTPProxy
metadata:
  name: sthlm-io
  namespace: sthlmio
spec:
  virtualhost:
    fqdn: sthlm.io
    tls:
      secretName: certificate-secret
  routes:
  - services:
    - name: web
      port: 8000
---
apiVersion: projectcontour.io/v1
kind: HTTPProxy
metadata:
  name: www-sthlm-io
  namespace: sthlmio
spec:
  virtualhost:
    fqdn: www.sthlm.io
    tls:
      secretName: certificate-secret
  routes:
  - requestRedirectPolicy:
      hostname: sthlm.io
      statusCode: 301
---
apiVersion: projectcontour.io/v1
kind: HTTPProxy
metadata:
  name: www-stockholm-io
  namespace: sthlmio
spec:
  virtualhost:
    fqdn: www.stockholm.io
    tls:
      secretName: certificate-secret
  routes:
  - requestRedirectPolicy:
      hostname: sthlm.io
      statusCode: 301
---
apiVersion: projectcontour.io/v1
kind: HTTPProxy
metadata:
  name: stockholm-io
  namespace: sthlmio
spec:
  virtualhost:
    fqdn: stockholm.io
    tls:
      secretName: certificate-secret
  routes:
  - requestRedirectPolicy:
      hostname: sthlm.io
      statusCode: 301
