apiVersion: apps/v1
kind: Deployment
metadata:
  name: web
  namespace: sthlmio
spec:
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
      annotations:
        config.alpha.linkerd.io/proxy-wait-before-exit-seconds: "40"
    spec:
      terminationGracePeriodSeconds: 60
      topologySpreadConstraints:
      - maxSkew: 1
        topologyKey: kubernetes.io/hostname
        whenUnsatisfiable: ScheduleAnyway
        labelSelector:
          matchLabels:
            app: web
      containers:
      - image: sthlmio/web:1.0.136 # {"$imagepolicy": "flux-system:sthlmio-web"}
        imagePullPolicy: IfNotPresent
        name: web
        ports:
        - containerPort: 8000
        resources:
          requests:
            memory: 10Mi
            cpu: 10m
          limits:
            memory: 50Mi
            cpu: 50m
        readinessProbe:
          httpGet:
            path: /ready
            port: 8001
          failureThreshold: 1
          initialDelaySeconds: 10
          periodSeconds: 1
          successThreshold: 1
          timeoutSeconds: 1
        livenessProbe:
          httpGet:
            path: /ready
            port: 8001
          failureThreshold: 3
          initialDelaySeconds: 15
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        lifecycle:
          preStop:
            exec:
              command: ["sleep", "30"]
