apiVersion: image.toolkit.fluxcd.io/v1alpha1
kind: ImageRepository
metadata:
  name: web-image
  namespace: sthlmio
spec:
  interval: 5m
  image: sthlmio/web
---
apiVersion: image.toolkit.fluxcd.io/v1alpha1
kind: ImagePolicy
metadata:
  name: web-policy
  namespace: sthlmio
spec:
  imageRepositoryRef:
    name: web-image
  policy:
    semver:
      range: v1.0.x
